name: Daily Auto Commit

on:
  schedule:
    - cron: '20 16 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install fortune
      run: sudo apt-get update && sudo apt-get install -y fortune-mod
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
    
    - name: Generate random commits
      run: |
        NUMBER=$((RANDOM % 23 + 1))
        echo "Gerando $NUMBER commits..."
        
        for ((run=1; run <= NUMBER; run++))
        do
          fortune > file.txt
          git add file.txt
          git commit -m "$(fortune -sn 32 | head -n 1)"
        done
    
    - name: Push changes
      run: git push
